const items = [
    {
      id: "001",
      image: "1.jpg",
      company: "Nivea",
      item_name: "Classic White Shirt",
      original_price: 500,
      current_price: 300,
      discount_percentage: 40,
      return_period: 30,
      delivery_date: "15 Oct 2023",
      rating: {
        stars: 4.5,
        count: 3500,
      },
    },
    {
      id: "002",
      image: "2.jpg",
      company: "Nivea",
      item_name: "Slim Fit Blue Shirt",
      original_price: 450,
      current_price: 225,
      discount_percentage: 50,
      return_period: 15,
      delivery_date: "20 Oct 2023",
      rating: {
        stars: 4.3,
        count: 4800,
      },
    },
    {
      id: "003",
      image: "3.jpg",
      company: "NUEVOSDAMAS",
      item_name: "Men Fresh Shirt",
      original_price: 285,
      current_price: 142,
      discount_percentage: 50,
      return_period: 14,
      delivery_date: "10 Oct 2023",
      rating: {
        stars: 4.2,
        count: 5200,
      },
    },
    {
      id: "004",
      image: "4.jpg",
      company: "ADIDAS",
  
      item_name: "Casual Check Shirt",
      original_price: 600,
      current_price: 360,
      discount_percentage: 40,
      return_period: 20,
      delivery_date: "25 Oct 2023",
      rating: {
        stars: 4.6,
        count: 4100,
      },
    },
    {
      id: "005",
      image: "5.jpg",
      company: "Nivea",
      item_name: "Formal Black Shirt",
      original_price: 700,
      current_price: 350,
      discount_percentage: 50,
      return_period: 10,
      delivery_date: "30 Oct 2023",
      rating: {
        stars: 4.1,
        count: 5300,
      },
    },
    {
      id: "006",
      image: "6.jpg",
      company: "Nivea",
      item_name: "Printed Casual Shirt",
      original_price: 650,
      current_price: 390,
      discount_percentage: 40,
      return_period: 25,
      delivery_date: "5 Nov 2023",
      rating: {
        stars: 4.4,
        count: 3200,
      },
    },
    {
      id: "007",
      image: "7.jpg",
      company: "Nivea",
      item_name: "Linen Summer Shirt",
      original_price: 800,
      current_price: 480,
      discount_percentage: 40,
      return_period: 14,
      delivery_date: "10 Nov 2023",
      rating: {
        stars: 4.7,
        count: 3000,
      },
    },
    {
      id: "008",
      image: "8.jpg",
      company: "Nivea",
      item_name: "Striped Office Shirt",
      original_price: 550,
      current_price: 275,
      discount_percentage: 50,
      return_period: 12,
      delivery_date: "15 Nov 2023",
      rating: {
        stars: 4.2,
        count: 4700,
      },
    },
    {
      company: "Nivea",
      image: "9.jpg",
      item_name: "Denim Casual Shirt",
      original_price: 900,
      current_price: 540,
      discount_percentage: 40,
      return_period: 18,
      delivery_date: "20 Nov 2023",
      rating: {
        stars: 4.5,
        count: 2900,
      },
    },
    {
      id: "010",
      image: "10.jpg",
      company: "Nivea",
      item_name: "Solid Green Shirt",
      original_price: 400,
      current_price: 200,
      discount_percentage: 50,
      return_period: 15,
      delivery_date: "25 Nov 2023",
      rating: {
        stars: 4.3,
        count: 4500,
      },
    },
    {
      id: "011",
      image: "11.jpg",
      company: "Nivea",
      item_name: "Party Wear Shirt",
      original_price: 1000,
      current_price: 600,
      discount_percentage: 40,
      return_period: 14,
      delivery_date: "30 Nov 2023",
      rating: {
        stars: 4.6,
        count: 3100,
      },
    },
    {
      id: "012",
      image: "12.jpg",
      company: "Nivea",
      item_name: "Cotton Comfort Shirt",
      original_price: 350,
      current_price: 175,
      discount_percentage: 50,
      return_period: 20,
      delivery_date: "5 Dec 2023",
      rating: {
        stars: 4.1,
        count: 5200,
      },
    },
  ];